### PR TITLE
Performance improvement in BZAR::smb_admin_file_share_test()

### PR DESCRIPTION
**Pull request by ckreibich**
Hi folks! Great scripts. Just a small performance tweak here: this short-cuts the check of each tree part so the function returns T right away if a part matches one of the admin share definitions, and F if none do. I haven't done performance measurements but I'd imagine for lengthy paths the difference is significant.

### CODE REVIEW

**Comment by johnwunder** [comment]
@ckreibich This looks great! Can you please review and sign-off on the [DCO](https://github.com/mitre-attack/car/blob/master/CONTRIBUTING.md)? You can just paste the following text: `DCO signed-off-by: <your name> <your email>`

**Comment by ckreibich** [comment]
You bet! DCO signed-off-by: Christian Kreibich <christian@corelight.com>

One question, John: the additions to the endpoints/operations you have in bzar_dce-rpc_consts.bro are fantastic. Do you prefer to keep these in BZAR, or could you see upstreaming them into the Zeek distribution? We'd for sure merge those.

**Comment by mfrndz** [comment]
Hi Christian, I think it would fantastic and appropriate to merge the RPC definitions into the Zeek distribution.  Thank you for suggesting it.

**Comment by ckreibich** [comment]
That's great, thanks @mfrndz — we can look out for a pull request from you, or put one together for you to review prior to merging. Either way you'll get full credit, of course. If you have a preferred way to proceed, just let us know. Thanks for being responsive!

**Comment by johnwunder** [comment]
@ckreibich To be honest it would be easier on our end if you could put together a PR for @mfrndz to review and sign off on. He/MITRE should get credit, I'm just the CAR Github person :smile:. Thank you!

**Comment by johnwunder** [comment]
In the meantime I'm gonna hit merge on this.

**Comment by ckreibich** [comment]
Right on folks, thanks! We'll get on the PR, and thanks for merging this.

**Comment by mfrndz** [comment]
Christian, sorry for the delay in my response.  Thank you for prepping the PR for this.  I'll keep an eye out for it.

Question: once you merge the new rpc endpoints and rpc operations, should I then remove bzar_dce-rpc_consts.bro from the BZAR scripts?  or would it be harmless to leave it in there?  (or should I just wrap it with a big @if to redef DCE_RPC::uuid_endpoint_map and DCE_RPC::operations only for earlier versions of Zeek?)

**Pull request merged**
