### PR TITLE
New Data Model : API

### PR DESCRIPTION
**Pull request by SJ029626**
This is a new Data model proposed by me referring http://cyboxproject.github.io/maturity-spectrum/.

### CODE REVIEW

**Comment by ikiril01** [comment]
@SJ029626 thanks for the submission! Do you have any examples of analytics or malicious behaviors that this would support the detection of?

**Comment by SJ029626** [comment]
Through understanding this technique of Mitre: https://attack.mitre.org/techniques/T1106/ I have come to this result. Well what I have suggested is for web but it can similarly be done for windows too. I propose you to make an car analytics on Web too if possible. Well coming to this data model it is correct in windows case too. So there is no problem. But if any more suggestions are there by you do give me. I will make those amendments.

**Comment by SJ029626** [comment]
Can we close this request as fast as possible @ikiril01 ?

**Comment by SJ029626** [comment]
> @SJ029626 thanks for the submission! Do you have any examples of analytics or malicious behaviors that this would support the detection of?

Hi @ikiril01 Through understanding this technique of Mitre: https://attack.mitre.org/techniques/T1106/ I have come to this result. But if any more suggestions are there by you do give me. I will make those amendments. Also, I have made some changes to make the data model more unified.

**Comment by ikiril01** [comment]
Thanks for the clarification @SJ029626. One of the primary goals of the CAR data model is to support the implementation of analytics that may currently be leveraged with respect to available data sources and detection tools/system instrumentation. I'm not aware of anything that's currently possible in this respect with regards to API calls - malware sandboxes may record them during the execution of a binary, but this generates a large amount of data for just a single binary. Until we have better capabilities of inspecting API calls on systems through EDR tools or related utilities, I don't think it makes sense to add this to CAR.

**Pull request closed without merging**
