### PR TITLE
CAR-2019-06-001: Lsass process dump via procdump

### PR DESCRIPTION
**Pull request by kp625544**

### CODE REVIEW

**Comment by ikiril01** [comment]
@kp625544 thanks for the submission! We're reviewing the analytic and will let you know if we have any questions or comments.

**Comment by ikiril01** [comment]
@kp625544 the analytic and Splunk search look quite good. My only question is about the text in the description - it mentions detecting both procdump and mimikatz. I'm assuming that this analytic is really only for procdump, which could be a precursor to running mimikatz?

**Comment by kp625544** [comment]
Hey @ikiril01 you're right. we are only detecting process dump via lsass and have made the necessary changes in the CAR analytic

**Comment by ikiril01** [comment]
@kp625544 thanks - I'm going to push this into a new branch and make some tweaks there before merging into master.

**Comment by kp625544** [comment]
@ikiril01 Can we have Cyware Labs as a contributor in the CAR?

**Comment by ikiril01** [comment]
@kp625544 no problem! I added Cyware Labs as a contributor for 2019-07-002.

**Pull request merged**
