### PR TITLE
Update for Zeek 2.6.x

### PR DESCRIPTION
**Pull request by peasead**
Updated `bzar_dce-rpc.bro` and `bzar_smb.bro` re: #4

### CODE REVIEW

**Comment by petiepooo** [comment]
Thanks for submitting this PR, @peasead.  I pulled your master branch in to test on my system, and I'm still getting this warning in stdout.log:

> warning in /opt/bro/share/bro/policy/protocols/smb/__load__.bro, line 1: deprecated script loaded from /opt/bro/share/bro/bzar/./main.bro:10 "Use '@load base/protocols/smb' instead"

Making the change to bzar/main.bro as the warning suggests makes it go away and everything appears to still be working.

This does, of course, break compatibility with Bro 2.5.5...  I don't think there's a way around that.

**Comment by johnwunder** [comment]
In terms of compatibility with older versions of Zeek...how about we make a branch to support 2.5 before merging?

**Comment by johnwunder** [comment]
Apparently @mfrndz discovered that you can use @if directive to target code at specific versions of Zeek. This would allow us to keep all code in the master branch and runnable across Zeek versions, so we'd like to go with that. @peasead thx for the PR...if you want to update it to do that go for it, otherwise I'll close this and we should be able to push something up in the next couple of days.

**Comment by johnwunder** [comment]
I threw up a separate shot at this here: https://github.com/mitre-attack/car/pull/14. I think we want the `@if` directives in both the load and in the code itself. Please review and if it looks good I'll merge. Thanks for looking into this!

**Comment by peasead** [comment]
Looks good to me, @johnwunder. Sorry to give you extra work 😬

**Comment by johnwunder** [comment]
Great, and no problem, thanks for getting it started! I'll go ahead and merge #14.

**Pull request closed without merging**
